dist: trusty
sudo: required
language: android
jdk:
  - oraclejdk8

android:
  components:
    # All the build system components should be at the latest version
    - tools
    - platform-tools
    - tools
    # Note that the tools section appears twice on purpose as it’s required
    # to get the newest Android SDK tools. Source: Travis CI docs.
    - build-tools-30.0.3

    # The libraries we can't get from Maven Central or similar
    - extra
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - yes | sdkmanager "platforms;android-30"
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - ./gradlew clean
  - chmod +x gradlew
  - ./gradlew dependencies || true
  - gem install bundler
  - bundle install
  - curl -sL firebase.tools | bash
  - bundle exec fastlane add_plugin firebase_app_distribution

script:
  - fastlane android beta