# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean")
    gradle(task: "assembleDebug")

    firebase_app_distribution(
       app: "1:185902714424:android:7dceae72a466e6404020cd",
       groups: "testers",
       firebase_cli_token: "1//0gRnPZXnPY-BhCgYIARAAGBASNwF-L9IrMfS1pjZfAedvN3kokFqso3tHXEh9gQa77J50y1vk-GVKr0wbroZgtAqWdYcuYoCiJ9c"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
